export const spreads = [
  {
    id: 1,
    title: "Tek Kart Açılımı",
    cards: "1",
    description: "Günlük enerji, hızlı mesaj, evet/hayır soruları",
  },
  {
    id: 2,
    title: "Üç Kart Açılımı",
    cards: "3",
    description: "Geçmiş-Şimdi-Gelecek, Durum-Engel-Tavsiye",
  },
  {
    id: 3,
    title: "Haftalık Açılım",
    cards: "7",
    description: "Haftanın her günü için rehberlik",
  },
  {
    id: 4,
    title: "Aşk Açılımı",
    cards: "5",
    description: "İlişki analizi, partner ile uyum",
  },
  {
    id: 5,
    title: "Kariyer Açılımı",
    cards: "5–7",
    description: "İş, para, fırsatlar ve engeller",
  },
  {
    id: 6,
    title: "Celtic Cross (Haç) Açılımı",
    cards: "10",
    description: "Derin ve detaylı genel hayat analizi",
  },
  {
    id: 7,
    title: "Yol Ayrımı Açılımı",
    cards: "6",
    description: "Karar vermek gereken iki yol arasında karşılaştırma",
  },
  {
    id: 8,
    title: "Yeni Ay Açılımı",
    cards: "6",
    description: "Yeni başlangıçlara özel enerji ve niyet okuması",
  },
  {
    id: 9,
    title: "Dolunay Açılımı",
    cards: "5",
    description: "Bırakılması gereken şeyler, kapanış enerjileri",
  },
  {
    id: 10,
    title: "Ruh Eşi Açılımı",
    cards: "6",
    description: "Ruh eşiyle ilgili enerji, yaklaşan ilişki",
  },
  {
    id: 11,
    title: "İlişki Açılımı",
    cards: "7",
    description: "Sen – O – Bağ – Engel – Tavsiye – Potansiyel – Gelecek",
  },
  {
    id: 12,
    title: "Spiritüel Rehberlik",
    cards: "5–7",
    description: "Ruhsal gelişim ve kişisel farkındalık",
  },
  {
    id: 13,
    title: "Çakra Açılımı",
    cards: "7",
    description: "Her çakra için bir kart – enerji dengesi analizi",
  },
  {
    id: 14,
    title: "Gölgelerle Yüzleşme",
    cards: "4",
    description: "Korkular, bastırılmış duygular, içsel çatışmalar",
  },
  {
    id: 15,
    title: "Hayat Amacı Açılımı",
    cards: "6",
    description: "Kader, potansiyel ve yön bulma",
  },
  {
    id: 16,
    title: "Karmik Ders Açılımı",
    cards: "5",
    description: "Geçmiş yaşamdan gelen etkiler",
  },
  {
    id: 17,
    title: "Engel ve Çözüm Açılımı",
    cards: "3–5",
    description: "Yaşanan sorunlar ve çözüm yolları",
  },
  {
    id: 18,
    title: "Dört Element Açılımı",
    cards: "4",
    description: "Ateş, Su, Hava, Toprak dengesi",
  },
  {
    id: 19,
    title: "Yıllık Açılım",
    cards: "12",
    description: "Her ay için bir kart – yıllık enerji haritası",
  },
  {
    id: 20,
    title: "Gelecek 6 Ay Açılımı",
    cards: "6",
    description: "Aylık genel yorum",
  },
  {
    id: 21,
    title: "İçsel Çocuk Açılımı",
    cards: "5",
    description: "Travmalar, iyileşme yolları",
  },
  {
    id: 22,
    title: "Ay Dönüşümü Açılımı",
    cards: "8",
    description: "Ay fazlarına göre niyet – bırakış – dönüşüm",
  },
  {
    id: 23,
    title: "İş ve Para Açılımı",
    cards: "6",
    description: "Finansal durum ve fırsatlar",
  },
  {
    id: 24,
    title: "Kendini Tanıma Açılımı",
    cards: "5",
    description: "Kişilik analizi, güçlü ve zayıf yönler",
  },
  {
    id: 25,
    title: "Arkadaşlık Açılımı",
    cards: "4–6",
    description: "Bir arkadaşlık ilişkisini değerlendirme",
  },
  {
    id: 26,
    title: "Anne-Baba İlişkisi",
    cards: "5",
    description: "Aile bağları ve etkileri",
  },
  {
    id: 27,
    title: "Rüya Yorumu Açılımı",
    cards: "3–5",
    description: "Görülen bir rüyanın anlamı ve mesajı",
  },
  {
    id: 28,
    title: "Soru-Cevap Açılımı",
    cards: "2",
    description: "Direkt soru – cevap tarzı",
  },
];
